/**
 * Synthesises src/data/signs.ts from the per-category files in src/data/_gen.
 * Strips build-only fields, sets `enabled`, wires confusion clusters, and
 * orders the deck. Run: npm run build-signs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const GEN_DIR = new URL('../src/data/_gen/', import.meta.url)
const OUT = new URL('../src/data/signs.ts', import.meta.url)

const CATEGORY_ORDER: Record<string, number> = {
  prohibitory: 0,
  mandatory: 1,
  warning: 2,
  information: 3,
  direction: 4,
  roadworks: 5,
  marking: 6,
  signal: 7,
}
const TIER_RANK: Record<string, number> = { core: 0, standard: 1, edge: 2 }

/** Bidirectional look-alike groups (the heart of "commonly confused with"). */
const CLUSTERS: string[][] = [
  ['no-entry', 'no-motor-vehicles', 'no-vehicles'],
  ['stop-and-give-way', 'give-way'],
  ['maximum-speed-limit', 'national-speed-limit', 'minimum-speed'],
  ['no-left-turn', 'turn-left-ahead', 'turn-left-at-junction', 'keep-left'],
  ['no-right-turn', 'turn-right-ahead', 'keep-right'],
  ['ahead-only', 'keep-left', 'keep-right', 'pass-either-side'],
  ['mini-roundabout', 'roundabout'],
  ['no-stopping-clearway', 'no-waiting'],
  ['two-way-traffic', 'one-way-traffic', 'two-way-traffic-crosses-a-one-way-road'],
  ['crossroads', 't-junction', 'staggered-junction', 'junction-priority-over-minor-road'],
  ['bend-to-the-right', 'double-bend-first-to-the-left'],
  ['road-narrows-on-both-sides', 'road-narrows-on-the-right', 'road-narrows-on-the-left'],
  [
    'level-crossing-with-barrier-or-gate-ahead',
    'level-crossing-without-barrier-or-gate-ahead',
    'trams-crossing-ahead',
  ],
  ['distance-to-give-way-line-ahead', 'distance-to-stop-line-ahead'],
  ['maximum-height', 'maximum-width', 'maximum-length', 'maximum-gross-weight'],
  [
    'children',
    'school-crossing-patrol-ahead',
    'pedestrians-in-road-ahead',
    'frail-or-disabled-pedestrians',
    'zebra-crossing-ahead',
  ],
  ['cattle', 'wild-animals', 'accompanied-horses-or-ponies'],
  ['slippery-road', 'risk-of-ice'],
  ['steep-hill-downwards', 'steep-hill-upwards'],
  ['no-cycling', 'route-for-pedal-cycles-only', 'cycle-route-ahead'],
  ['parking', 'parking-solo-motorcycles', 'parking-restricted-to-permit-holders'],
  ['tunnel-ahead', 'opening-or-swing-bridge-ahead', 'hump-bridge'],
  ['give-way', 'give-priority-to-oncoming-vehicles'],
]

interface Raw {
  id: string
  caption: string
  category: string
  tier: string
  shape: string
  colour: string
  diagram?: string
  asset?: string
  composite?: boolean
  explanation: string
  mnemonic?: string
  searchTerms?: string[]
}

const raw: Raw[] = []
for (const f of readdirSync(GEN_DIR).sort()) {
  if (!f.endsWith('.json')) continue
  const arr = JSON.parse(readFileSync(new URL(f, GEN_DIR), 'utf8')) as Raw[]
  raw.push(...arr)
}

const ids = new Set(raw.map((s) => s.id))

// build confusedWith map from clusters (only ids that exist), capped at 4
const confused = new Map<string, string[]>()
for (const group of CLUSTERS) {
  const present = group.filter((id) => ids.has(id))
  for (const id of present) {
    const list = confused.get(id) ?? []
    for (const other of present) if (other !== id && !list.includes(other)) list.push(other)
    confused.set(id, list)
  }
}

// warn about any cluster ids that don't exist (typos)
for (const group of CLUSTERS) {
  for (const id of group) if (!ids.has(id)) console.warn(`⚠ cluster references unknown id: ${id}`)
}

raw.sort(
  (a, b) =>
    (CATEGORY_ORDER[a.category] ?? 9) - (CATEGORY_ORDER[b.category] ?? 9) ||
    (TIER_RANK[a.tier] ?? 9) - (TIER_RANK[b.tier] ?? 9) ||
    a.caption.localeCompare(b.caption),
)

const clean = raw.map((s) => {
  const o: Record<string, unknown> = {
    id: s.id,
    caption: s.caption,
    category: s.category,
    tier: s.tier,
    enabled: s.tier !== 'edge',
    shape: s.shape,
    colour: s.colour,
    asset: s.composite ? '' : s.asset ?? '',
  }
  if (s.composite) o.composite = true
  if (s.diagram) o.diagram = s.diagram
  o.explanation = s.explanation
  if (s.mnemonic) o.mnemonic = s.mnemonic
  o.confusedWith = (confused.get(s.id) ?? []).slice(0, 4)
  o.searchTerms = s.searchTerms ?? []
  return o
})

const header = `import type { SignDefinition } from '../lib/types'

/* AUTO-GENERATED by scripts/build-signs.ts from src/data/_gen/*.json.
 * Do not edit by hand — edit the generators / _gen sources and re-run
 * \`npm run build-signs\`. ${clean.length} signs. */

export const signs: SignDefinition[] = `

writeFileSync(OUT, header + JSON.stringify(clean, null, 2) + '\n')

const enabled = clean.filter((s) => s.enabled).length
const composite = clean.filter((s) => s.composite).length
console.log(
  `Wrote ${clean.length} signs (${enabled} enabled by default, ${clean.length - enabled} edge, ${composite} composite) → src/data/signs.ts`,
)
