import type { SignDefinition } from '../lib/types'

/* AUTO-GENERATED by scripts/build-signs.ts from src/data/_gen/*.json.
 * Do not edit by hand — edit the generators / _gen sources and re-run
 * `npm run build-signs`. 118 signs. */

export const signs: SignDefinition[] = [
  {
    "id": "entry-to-20-mph-zone",
    "caption": "Entry to 20 mph zone",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "white sign, 20 roundel and 'ZONE'",
    "asset": "UK_traffic_sign_674.svg",
    "diagram": "674",
    "explanation": "You are entering a 20 mph zone with traffic-calming measures; keep to 20 mph until you see the end-of-zone sign.",
    "mnemonic": "ZONE word means it lasts, not just one limit.",
    "confusedWith": [],
    "searchTerms": [
      "20 mph zone",
      "twenty zone entry",
      "20 zone sign",
      "speed zone start",
      "traffic calming sign"
    ]
  },
  {
    "id": "give-way",
    "caption": "Give way to traffic on major road",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "inverted-triangle",
    "colour": "red-bordered inverted triangle, white centre",
    "asset": "UK_traffic_sign_602.svg",
    "diagram": "602",
    "explanation": "Give way to traffic on the major road and only emerge when there is a safe gap; you need not stop if the way is clear.",
    "mnemonic": "Upside-down triangle = give way.",
    "confusedWith": [
      "stop-and-give-way",
      "give-priority-to-oncoming-vehicles"
    ],
    "searchTerms": [
      "give way",
      "yield",
      "upside down triangle",
      "red triangle pointing down",
      "junction priority"
    ]
  },
  {
    "id": "maximum-speed-limit",
    "caption": "Maximum speed limit",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, black number on white",
    "asset": "UK_traffic_sign_670V30.svg",
    "diagram": "670",
    "explanation": "Do not exceed the speed shown (here 30 mph); the limit applies until a different limit or the national speed limit sign is seen.",
    "mnemonic": "Red ring round a number = your ceiling speed.",
    "confusedWith": [
      "national-speed-limit",
      "minimum-speed"
    ],
    "searchTerms": [
      "speed limit",
      "30 mph sign",
      "red circle number",
      "maximum speed",
      "mph sign"
    ]
  },
  {
    "id": "national-speed-limit",
    "caption": "National speed limit applies",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "white circle, black diagonal stripe",
    "asset": "UK_traffic_sign_671.svg",
    "diagram": "671",
    "explanation": "The national speed limit now applies for your vehicle and road type; know your limit, as a motorcycle is 60 mph on a single carriageway and 70 mph on a dual carriageway.",
    "mnemonic": "Black slash on white = national limit, you decide the number.",
    "confusedWith": [
      "maximum-speed-limit",
      "minimum-speed"
    ],
    "searchTerms": [
      "national speed limit",
      "black diagonal line",
      "white circle slash",
      "derestriction sign",
      "end of speed limit"
    ]
  },
  {
    "id": "no-entry",
    "caption": "No entry for vehicular traffic",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "white horizontal bar on red circle",
    "asset": "UK_traffic_sign_616.svg",
    "diagram": "616",
    "explanation": "Vehicles must not pass beyond this sign; it usually marks the exit of a one-way street, so do not enter.",
    "mnemonic": "Red circle, white bar = barred from entry.",
    "confusedWith": [
      "no-motor-vehicles",
      "no-vehicles"
    ],
    "searchTerms": [
      "no entry",
      "red circle white line",
      "do not enter",
      "one way exit",
      "white bar red sign"
    ]
  },
  {
    "id": "no-left-turn",
    "caption": "No left turn",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, black left arrow crossed out",
    "asset": "UK_traffic_sign_613.svg",
    "diagram": "613",
    "explanation": "Turning left is prohibited at this junction; carry on or find an alternative route.",
    "mnemonic": "Left arrow struck through = no left.",
    "confusedWith": [
      "turn-left-ahead",
      "turn-left-at-junction",
      "keep-left"
    ],
    "searchTerms": [
      "no left turn",
      "left turn prohibited",
      "arrow crossed out left",
      "cannot turn left",
      "no turning left"
    ]
  },
  {
    "id": "no-motor-vehicles",
    "caption": "No motor vehicles",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, black car and motorcycle",
    "asset": "UK_traffic_sign_619.svg",
    "diagram": "619",
    "explanation": "Motor vehicles, including motorcycles, are prohibited beyond this point; do not ride through.",
    "mnemonic": "Car and bike crossed out = no engines allowed.",
    "confusedWith": [
      "no-entry",
      "no-vehicles"
    ],
    "searchTerms": [
      "no motor vehicles",
      "no cars or motorbikes",
      "car and motorcycle symbol",
      "motor vehicles prohibited",
      "no engines"
    ]
  },
  {
    "id": "no-overtaking",
    "caption": "No overtaking",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, red car beside black car",
    "asset": "UK_traffic_sign_632.svg",
    "diagram": "632",
    "explanation": "Overtaking is prohibited until you pass an end sign; stay in lane and do not pull out to pass.",
    "mnemonic": "Red car can't pass black car.",
    "confusedWith": [],
    "searchTerms": [
      "no overtaking",
      "two cars sign",
      "do not pass",
      "red car black car",
      "overtaking prohibited"
    ]
  },
  {
    "id": "no-right-turn",
    "caption": "No right turn",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, black right arrow crossed out",
    "asset": "UK_traffic_sign_612.svg",
    "diagram": "612",
    "explanation": "Turning right is prohibited at this junction; carry on or find an alternative route.",
    "mnemonic": "Right arrow struck through = no right.",
    "confusedWith": [
      "turn-right-ahead",
      "keep-right"
    ],
    "searchTerms": [
      "no right turn",
      "right turn prohibited",
      "arrow crossed out right",
      "cannot turn right",
      "no turning right"
    ]
  },
  {
    "id": "no-stopping-clearway",
    "caption": "No stopping (clearway)",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, red border and red cross",
    "asset": "UK_traffic_sign_642.svg",
    "diagram": "642",
    "explanation": "You must not stop on the main carriageway at any time, even to set down or pick up; this is a clearway.",
    "mnemonic": "Red X means no stopping at all.",
    "confusedWith": [
      "no-waiting"
    ],
    "searchTerms": [
      "clearway",
      "no stopping",
      "red cross blue circle",
      "no stopping any time",
      "red x sign"
    ]
  },
  {
    "id": "no-u-turn",
    "caption": "No U-turn",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, black U-turn arrow",
    "asset": "UK_traffic_sign_614.svg",
    "diagram": "614",
    "explanation": "You must not make a U-turn here; continue and turn round elsewhere where it is permitted and safe.",
    "mnemonic": "U-arrow with a red ring = no turning back.",
    "confusedWith": [],
    "searchTerms": [
      "no u turn",
      "u turn prohibited",
      "no turning around",
      "u shaped arrow crossed",
      "no reverse direction"
    ]
  },
  {
    "id": "stop-and-give-way",
    "caption": "Stop and give way",
    "category": "prohibitory",
    "tier": "core",
    "enabled": true,
    "shape": "octagon",
    "colour": "white STOP on red octagon",
    "asset": "UK_traffic_sign_601.1.svg",
    "diagram": "601.1",
    "explanation": "You must stop completely at the line and only move off when it is safe; the road ahead has restricted visibility.",
    "mnemonic": "Only octagon on UK roads means STOP every time.",
    "confusedWith": [
      "give-way"
    ],
    "searchTerms": [
      "stop sign",
      "red octagon",
      "stop and give way",
      "eight sided red sign",
      "halt"
    ]
  },
  {
    "id": "end-of-20-mph-zone",
    "caption": "End of 20 mph zone",
    "category": "prohibitory",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "white sign, grey 20 roundel and 30 limit",
    "asset": "UK_traffic_sign_675.svg",
    "diagram": "675",
    "explanation": "The 20 mph zone has ended and a new limit (commonly 30 mph) now applies; adjust your speed to the limit shown.",
    "mnemonic": "Greyed-out 20 = zone is over.",
    "confusedWith": [],
    "searchTerms": [
      "end of 20 zone",
      "20 zone ends",
      "start of 30 zone",
      "grey 20 sign",
      "end speed zone"
    ]
  },
  {
    "id": "give-priority-to-oncoming-vehicles",
    "caption": "Give priority to oncoming vehicles",
    "category": "prohibitory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "white circle, red border, red and black arrows",
    "asset": "UK_traffic_sign_615.svg",
    "diagram": "615",
    "explanation": "Priority must be given to oncoming vehicles at a narrow section; wait and let approaching traffic through before you proceed.",
    "mnemonic": "Big red arrow points at you, so you give way.",
    "confusedWith": [
      "give-way"
    ],
    "searchTerms": [
      "give priority oncoming",
      "narrow road priority",
      "red arrow black arrow",
      "give way to oncoming",
      "priority over oncoming opposite"
    ]
  },
  {
    "id": "maximum-gross-weight",
    "caption": "Maximum gross weight",
    "category": "prohibitory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, weight in tonnes (black on white)",
    "asset": "UK_traffic_sign_626.1.svg",
    "diagram": "626.1",
    "explanation": "No vehicle over the gross weight shown (in tonnes) may pass, typically protecting a weak bridge or structure; do not proceed if you are over the limit.",
    "mnemonic": "Just a weight, no lorry = applies to every vehicle.",
    "confusedWith": [
      "maximum-height",
      "maximum-width",
      "maximum-length"
    ],
    "searchTerms": [
      "maximum gross weight",
      "weight limit sign",
      "weak bridge weight",
      "tonnes limit red circle",
      "no vehicles over weight"
    ]
  },
  {
    "id": "maximum-height",
    "caption": "Maximum height",
    "category": "prohibitory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, height figure in black",
    "asset": "UK_traffic_sign_629.2.svg",
    "diagram": "629.2",
    "explanation": "Vehicles taller than the height shown must not proceed; if your machine plus load exceeds it, find another route.",
    "mnemonic": "Number with arrows top and bottom = how tall you can be.",
    "confusedWith": [
      "maximum-width",
      "maximum-length",
      "maximum-gross-weight"
    ],
    "searchTerms": [
      "maximum height",
      "low bridge height",
      "height limit sign",
      "vehicle height restriction",
      "max height feet"
    ]
  },
  {
    "id": "maximum-width",
    "caption": "Maximum width",
    "category": "prohibitory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, width figure with side arrows",
    "asset": "UK_traffic_sign_629.svg",
    "diagram": "629",
    "explanation": "Vehicles wider than the width shown must not proceed; check your width including mirrors and load before continuing.",
    "mnemonic": "Arrows pointing in from each side = how wide you can be.",
    "confusedWith": [
      "maximum-height",
      "maximum-length",
      "maximum-gross-weight"
    ],
    "searchTerms": [
      "maximum width",
      "width limit sign",
      "narrow road width",
      "vehicle width restriction",
      "max width feet"
    ]
  },
  {
    "id": "no-cycling",
    "caption": "No cycling",
    "category": "prohibitory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "red circle, black bicycle",
    "asset": "UK_traffic_sign_951.svg",
    "diagram": "951",
    "explanation": "Riding pedal cycles is prohibited beyond this sign; cyclists must dismount or use another route.",
    "mnemonic": "Bicycle in a red ring = no riding here.",
    "confusedWith": [
      "route-for-pedal-cycles-only",
      "cycle-route-ahead"
    ],
    "searchTerms": [
      "no cycling",
      "no bikes",
      "bicycle prohibited",
      "cycling not allowed",
      "no bicycles sign"
    ]
  },
  {
    "id": "no-waiting",
    "caption": "No waiting",
    "category": "prohibitory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, red border and single red diagonal",
    "asset": "UK_traffic_sign_636.svg",
    "diagram": "636",
    "explanation": "You must not wait or park here, though you may stop briefly to load, unload, or set down passengers.",
    "mnemonic": "One red stroke = no waiting; two strokes (cross) = no stopping.",
    "confusedWith": [
      "no-stopping-clearway"
    ],
    "searchTerms": [
      "no waiting",
      "blue circle red line",
      "no parking",
      "single red diagonal",
      "waiting restriction"
    ]
  },
  {
    "id": "maximum-length",
    "caption": "Maximum length",
    "category": "prohibitory",
    "tier": "edge",
    "enabled": false,
    "shape": "circle",
    "colour": "red circle, length figure with arrows",
    "asset": "UK_traffic_sign_629.1.svg",
    "diagram": "629.1",
    "explanation": "Vehicles longer than the length shown must not proceed; measure your machine plus any trailer before continuing.",
    "mnemonic": "Arrows front and back = how long you can be.",
    "confusedWith": [
      "maximum-height",
      "maximum-width",
      "maximum-gross-weight"
    ],
    "searchTerms": [
      "maximum length",
      "length limit sign",
      "vehicle length restriction",
      "max length feet",
      "long vehicle prohibited"
    ]
  },
  {
    "id": "no-goods-vehicles-over-weight",
    "caption": "No goods vehicles over weight shown",
    "category": "prohibitory",
    "tier": "edge",
    "enabled": false,
    "shape": "circle",
    "colour": "red circle, black lorry with weight figure",
    "asset": "UK_traffic_sign_622.1A.svg",
    "diagram": "622.1A",
    "explanation": "Goods vehicles over the maximum gross weight shown are prohibited, except for access or loading; lighter vehicles and cars may still pass.",
    "mnemonic": "Lorry plus weight = only heavy goods vehicles are banned.",
    "confusedWith": [],
    "searchTerms": [
      "no lorries over weight",
      "hgv weight limit",
      "goods vehicle weight restriction",
      "7.5 tonne lorry sign",
      "no trucks over weight"
    ]
  },
  {
    "id": "no-pedestrians",
    "caption": "No pedestrians",
    "category": "prohibitory",
    "tier": "edge",
    "enabled": false,
    "shape": "circle",
    "colour": "red circle, black walking figure",
    "asset": "UK_traffic_sign_625.1.svg",
    "diagram": "625.1",
    "explanation": "Pedestrians are prohibited beyond this sign, for example on a slip road or in a tunnel; walking here is not allowed.",
    "mnemonic": "Walker in a red ring = no walking.",
    "confusedWith": [],
    "searchTerms": [
      "no pedestrians",
      "pedestrians prohibited",
      "no walking",
      "walking figure crossed",
      "no foot traffic"
    ]
  },
  {
    "id": "no-towed-caravans",
    "caption": "No towed caravans",
    "category": "prohibitory",
    "tier": "edge",
    "enabled": false,
    "shape": "circle",
    "colour": "red circle, black caravan",
    "asset": "UK_traffic_sign_622.7.svg",
    "diagram": "622.7",
    "explanation": "Towed caravans are prohibited beyond this point; if you are towing one, take an alternative route.",
    "mnemonic": "Caravan in a red ring = leave the van behind.",
    "confusedWith": [],
    "searchTerms": [
      "no caravans",
      "towed caravan prohibited",
      "no towing caravan",
      "caravan symbol red circle",
      "no trailer caravan"
    ]
  },
  {
    "id": "no-vehicles",
    "caption": "No vehicles",
    "category": "prohibitory",
    "tier": "edge",
    "enabled": false,
    "shape": "circle",
    "colour": "red circle, plain white centre",
    "asset": "UK_traffic_sign_617.svg",
    "diagram": "617",
    "explanation": "No vehicles of any kind may pass, except those being pushed by hand by a pedestrian; do not ride or drive through.",
    "mnemonic": "Empty red ring = no vehicles at all.",
    "confusedWith": [
      "no-entry",
      "no-motor-vehicles"
    ],
    "searchTerms": [
      "no vehicles",
      "all vehicles prohibited",
      "empty red circle",
      "blank red ring sign",
      "no traffic"
    ]
  },
  {
    "id": "parking-restricted-to-permit-holders",
    "caption": "Parking restricted to permit holders",
    "category": "prohibitory",
    "tier": "edge",
    "enabled": false,
    "shape": "rectangle",
    "colour": "white sign, blue 'permit holders only' panel",
    "asset": "UK_traffic_sign_660.svg",
    "diagram": "660",
    "explanation": "Parking here is reserved for permit holders only; do not park unless you hold a valid permit for the zone.",
    "mnemonic": "Permit holders only means no permit, no parking.",
    "confusedWith": [
      "parking",
      "parking-solo-motorcycles"
    ],
    "searchTerms": [
      "permit holders only",
      "permit parking",
      "residents parking only",
      "no parking without permit",
      "parking permit zone"
    ]
  },
  {
    "id": "ahead-only",
    "caption": "Ahead only",
    "category": "mandatory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white upward arrow",
    "asset": "UK_traffic_sign_606_(ahead).svg",
    "diagram": "606",
    "explanation": "You must continue straight ahead in the direction of the arrow; turning is not permitted here. Keep moving forward and do not turn off.",
    "mnemonic": "Blue means do; arrow up means go straight through.",
    "confusedWith": [
      "keep-left",
      "keep-right",
      "pass-either-side"
    ],
    "searchTerms": [
      "straight ahead",
      "go straight",
      "blue arrow up",
      "ahead only",
      "no turning"
    ]
  },
  {
    "id": "keep-left",
    "caption": "Keep left",
    "category": "mandatory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white arrow pointing left",
    "asset": "UK_traffic_sign_610.svg",
    "diagram": "610",
    "explanation": "You must pass to the left of the sign, for example at a central island or obstruction. Keep to the left-hand side.",
    "mnemonic": "Horizontal arrow = pass that side now (left), not a turn ahead.",
    "confusedWith": [
      "no-left-turn",
      "turn-left-ahead",
      "turn-left-at-junction",
      "ahead-only"
    ],
    "searchTerms": [
      "keep left",
      "pass left of island",
      "blue arrow left",
      "bollard keep left",
      "left of obstruction"
    ]
  },
  {
    "id": "keep-right",
    "caption": "Keep right",
    "category": "mandatory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white arrow pointing right",
    "asset": "UK_traffic_sign_610_(right).svg",
    "diagram": "610",
    "explanation": "You must pass to the right of the sign, for example at a central island or obstruction. Keep to the right-hand side.",
    "mnemonic": "Horizontal arrow = pass that side now (right), not a turn ahead.",
    "confusedWith": [
      "no-right-turn",
      "turn-right-ahead",
      "ahead-only",
      "keep-left"
    ],
    "searchTerms": [
      "keep right",
      "pass right of island",
      "blue arrow right",
      "bollard keep right",
      "right of obstruction"
    ]
  },
  {
    "id": "mini-roundabout",
    "caption": "Mini-roundabout",
    "category": "mandatory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, three white curved arrows clockwise",
    "asset": "UK_traffic_sign_611.1.svg",
    "diagram": "611.1",
    "explanation": "A mini-roundabout is ahead: give way to traffic coming from your right and go round it clockwise. Slow down and be ready to give way.",
    "mnemonic": "Round arrows = go round; always give way to the right.",
    "confusedWith": [
      "roundabout"
    ],
    "searchTerms": [
      "mini roundabout",
      "small roundabout",
      "give way right",
      "circular arrows blue",
      "roundabout clockwise"
    ]
  },
  {
    "id": "pass-either-side",
    "caption": "Pass either side",
    "category": "mandatory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, two white arrows up-left and up-right",
    "asset": "UK_traffic_sign_611.svg",
    "diagram": "611",
    "explanation": "You may pass on either side of the obstruction or island ahead to reach the same destination. Choose a clear side and pass safely.",
    "mnemonic": "Two arrows splitting = take either side, they meet again.",
    "confusedWith": [
      "ahead-only",
      "keep-left",
      "keep-right"
    ],
    "searchTerms": [
      "pass either side",
      "two arrows blue",
      "split arrows",
      "either side of island",
      "left or right pass"
    ]
  },
  {
    "id": "route-for-pedal-cycles-only",
    "caption": "Route for pedal cycles only",
    "category": "mandatory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white bicycle",
    "asset": "UK_traffic_sign_955.svg",
    "diagram": "955",
    "explanation": "This route is for pedal cycles only; motor vehicles must not use it. As a rider, do not enter on your motorcycle.",
    "mnemonic": "Blue circle, bike only = pedal power, no engines.",
    "confusedWith": [
      "no-cycling",
      "cycle-route-ahead"
    ],
    "searchTerms": [
      "cycle route only",
      "bicycle only path",
      "blue bike sign",
      "pedal cycles only",
      "cycle track"
    ]
  },
  {
    "id": "turn-left-ahead",
    "caption": "Turn left ahead",
    "category": "mandatory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white arrow angled up-left",
    "asset": "UK_traffic_sign_609.svg",
    "diagram": "609",
    "explanation": "You must turn left at the junction ahead; the angled arrow warns the turn is coming up. Prepare to turn left.",
    "mnemonic": "Arrow leaning forward-left = the left turn is just ahead.",
    "confusedWith": [
      "no-left-turn",
      "turn-left-at-junction",
      "keep-left"
    ],
    "searchTerms": [
      "turn left ahead",
      "blue turn left",
      "left turn coming",
      "mandatory left",
      "left arrow sign"
    ]
  },
  {
    "id": "turn-right-ahead",
    "caption": "Turn right ahead",
    "category": "mandatory",
    "tier": "core",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white arrow angled up-right",
    "asset": "UK_traffic_sign_609_(right).svg",
    "diagram": "609",
    "explanation": "You must turn right at the junction ahead; the angled arrow warns the turn is coming up. Prepare to turn right.",
    "mnemonic": "Arrow leaning forward-right = the right turn is just ahead.",
    "confusedWith": [
      "no-right-turn",
      "keep-right"
    ],
    "searchTerms": [
      "turn right ahead",
      "blue turn right",
      "right turn coming",
      "mandatory right",
      "right arrow sign"
    ]
  },
  {
    "id": "buses-and-cycles-only",
    "caption": "Buses and cycles only",
    "category": "mandatory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white bus and white bicycle",
    "asset": "UK_traffic_sign_953.svg",
    "diagram": "953",
    "explanation": "This route is for buses and pedal cycles only; other motor vehicles must not use it. Do not enter on your motorcycle.",
    "mnemonic": "Bus + bike in blue = only these two belong.",
    "confusedWith": [],
    "searchTerms": [
      "buses and cycles only",
      "bus and bike lane",
      "blue bus bicycle",
      "bus cycle route",
      "no cars bus lane"
    ]
  },
  {
    "id": "end-of-minimum-speed",
    "caption": "End of minimum speed",
    "category": "mandatory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white number with red diagonal line",
    "asset": "UK_traffic_sign_673.svg",
    "diagram": "673",
    "explanation": "The minimum speed limit no longer applies from this point. You are free to travel below that figure if needed.",
    "mnemonic": "Red slash through it = that rule is now crossed out.",
    "confusedWith": [],
    "searchTerms": [
      "end of minimum speed",
      "minimum speed ends",
      "blue speed crossed out",
      "red line through speed",
      "no more minimum speed"
    ]
  },
  {
    "id": "minimum-speed",
    "caption": "Minimum speed",
    "category": "mandatory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white number (e.g. 30)",
    "asset": "UK_traffic_sign_672.svg",
    "diagram": "672",
    "explanation": "You must not drive slower than the speed shown unless conditions make it unsafe. Keep your speed at or above this figure.",
    "mnemonic": "Blue = must do; so you must do at least this speed.",
    "confusedWith": [
      "maximum-speed-limit",
      "national-speed-limit"
    ],
    "searchTerms": [
      "minimum speed",
      "blue speed sign",
      "must go this fast",
      "30 blue circle",
      "minimum speed limit"
    ]
  },
  {
    "id": "segregated-pedal-cycle-and-pedestrian-route",
    "caption": "Segregated pedal cycle and pedestrian route",
    "category": "mandatory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, bicycle and pedestrian split by white vertical line",
    "asset": "UK_traffic_sign_957.svg",
    "diagram": "957",
    "explanation": "A shared route where cyclists and pedestrians have separate sides divided by a line; each must keep to their own side. Motor vehicles must not enter.",
    "mnemonic": "Line down the middle = stay in your lane, segregated.",
    "confusedWith": [],
    "searchTerms": [
      "segregated cycle path",
      "bike and walk separate",
      "divided cycle footway",
      "cyclist pedestrian line",
      "split path sign"
    ]
  },
  {
    "id": "shared-cycle-and-pedestrian-route",
    "caption": "Shared cycle and pedestrian route",
    "category": "mandatory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, bicycle above pedestrian, no dividing line",
    "asset": "UK_traffic_sign_956.svg",
    "diagram": "956",
    "explanation": "A route shared by cyclists and pedestrians with no separation; both use the same space, so cyclists must give way considerately. Motor vehicles must not enter.",
    "mnemonic": "No line = shared space, watch out for each other.",
    "confusedWith": [],
    "searchTerms": [
      "shared cycle path",
      "bike and pedestrian shared",
      "shared use path",
      "cyclist walker together",
      "no line cycle sign"
    ]
  },
  {
    "id": "turn-left-at-junction",
    "caption": "Turn left at junction",
    "category": "mandatory",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "blue circle, white arrow pointing left",
    "asset": "UK_traffic_sign_606.svg",
    "diagram": "606",
    "explanation": "At the junction you must turn left; the horizontal arrow shows the turn is here, not further ahead. Turn left now.",
    "mnemonic": "Flat arrow = turn here; angled arrow (609) = ahead.",
    "confusedWith": [
      "no-left-turn",
      "turn-left-ahead",
      "keep-left"
    ],
    "searchTerms": [
      "turn left",
      "mandatory left turn",
      "blue left arrow junction",
      "left only",
      "must turn left"
    ]
  },
  {
    "id": "contra-flow-bus-lane",
    "caption": "Contra-flow bus lane",
    "category": "mandatory",
    "tier": "edge",
    "enabled": false,
    "shape": "rectangle",
    "colour": "blue rectangle, white bus and upward arrow against traffic flow",
    "asset": "UK_traffic_sign_960.svg",
    "diagram": "960",
    "explanation": "Ahead, buses travel towards you in a lane running against the normal traffic flow; expect oncoming buses and do not enter that lane. Stay in your correct lane.",
    "mnemonic": "Contra = against; the bus arrow faces back at you.",
    "confusedWith": [],
    "searchTerms": [
      "contra flow bus lane",
      "buses coming towards you",
      "oncoming bus lane",
      "blue bus arrow sign",
      "bus lane against traffic"
    ]
  },
  {
    "id": "trams-only",
    "caption": "Trams only",
    "category": "mandatory",
    "tier": "edge",
    "enabled": false,
    "shape": "circle",
    "colour": "blue circle, white tram",
    "asset": "UK_traffic_sign_953.1.svg",
    "diagram": "953.1",
    "explanation": "This route is for trams only; all other vehicles are prohibited. Never enter a tram-only route on your motorcycle.",
    "mnemonic": "Blue circle, tram only = rails, not road for you.",
    "confusedWith": [],
    "searchTerms": [
      "trams only",
      "tram route",
      "blue tram sign",
      "tramcar only",
      "no cars trams"
    ]
  },
  {
    "id": "with-flow-bus-lane",
    "caption": "With-flow bus lane",
    "category": "mandatory",
    "tier": "edge",
    "enabled": false,
    "shape": "rectangle",
    "colour": "blue rectangle, white bus, cycle (and 'taxi'), with operating times",
    "asset": "",
    "composite": true,
    "diagram": "958",
    "explanation": "A bus lane runs ahead in the same direction as the traffic flow, usually with a cycle (and sometimes taxi) symbol and its hours of operation; do not drive in it during those times. Stay in the general traffic lane.",
    "mnemonic": "With-flow = bus goes your way; check the times before using it.",
    "confusedWith": [],
    "searchTerms": [
      "with flow bus lane",
      "bus lane ahead",
      "bus lane times",
      "blue bus lane sign",
      "bus cycle taxi lane"
    ]
  },
  {
    "id": "bend-to-the-right",
    "caption": "Bend to the right",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black right-curving arrow",
    "asset": "UK_traffic_sign_512.svg",
    "diagram": "512",
    "explanation": "The road bends sharply to the right ahead; reduce speed before the bend and keep to your side of the road.",
    "mnemonic": "Arrow leans the way the road goes.",
    "confusedWith": [
      "double-bend-first-to-the-left"
    ],
    "searchTerms": [
      "bend right",
      "sharp right bend",
      "right curve ahead",
      "road curves right",
      "corner right"
    ]
  },
  {
    "id": "children",
    "caption": "Children (school or playground)",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black symbol of two children walking",
    "asset": "UK_traffic_sign_545.svg",
    "diagram": "545",
    "explanation": "Children may be crossing on their way to or from a school or playground; slow down and watch carefully for them stepping out.",
    "mnemonic": "Two kids = keep it slow.",
    "confusedWith": [
      "school-crossing-patrol-ahead",
      "pedestrians-in-road-ahead",
      "frail-or-disabled-pedestrians",
      "zebra-crossing-ahead"
    ],
    "searchTerms": [
      "children",
      "school sign",
      "kids crossing",
      "two children walking",
      "playground"
    ]
  },
  {
    "id": "crossroads",
    "caption": "Crossroads",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black crossroads symbol",
    "asset": "UK_traffic_sign_504.1.svg",
    "diagram": "504.1",
    "explanation": "Roads cross ahead with no priority shown; slow down, look both ways and be ready to give way to traffic on the other road.",
    "mnemonic": "Plus sign means roads plus across.",
    "confusedWith": [
      "t-junction",
      "staggered-junction",
      "junction-priority-over-minor-road"
    ],
    "searchTerms": [
      "crossroads",
      "roads cross ahead",
      "intersection sign",
      "junction ahead",
      "four ways meet"
    ]
  },
  {
    "id": "cycle-route-ahead",
    "caption": "Cycle route ahead",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black bicycle symbol on white",
    "asset": "UK_traffic_sign_950.svg",
    "diagram": "950",
    "explanation": "Cyclists may be crossing or joining the road ahead on a cycle route; look out for them and give them room.",
    "mnemonic": "Bike in a triangle = cyclists about.",
    "confusedWith": [
      "no-cycling",
      "route-for-pedal-cycles-only"
    ],
    "searchTerms": [
      "cycle route",
      "bicycle sign",
      "cyclists ahead",
      "bike crossing",
      "cycle path"
    ]
  },
  {
    "id": "double-bend-first-to-the-left",
    "caption": "Double bend, first to the left",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black S-shaped arrow bending left first",
    "asset": "UK_traffic_sign_513.svg",
    "diagram": "513",
    "explanation": "A double bend or series of bends ahead, the first to the left; slow down and stay in lane through the bends.",
    "mnemonic": "S-curve starts by leaning left.",
    "confusedWith": [
      "bend-to-the-right"
    ],
    "searchTerms": [
      "double bend",
      "s bend left first",
      "series of bends",
      "winding road left",
      "two bends ahead"
    ]
  },
  {
    "id": "dual-carriageway-ends",
    "caption": "Dual carriageway ends",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black road symbol merging from two lanes to one",
    "asset": "UK_traffic_sign_520.svg",
    "diagram": "520",
    "explanation": "The dual carriageway ends and becomes a single two-way road ahead; reduce speed and expect oncoming traffic.",
    "mnemonic": "Two lanes pinch back into one.",
    "confusedWith": [],
    "searchTerms": [
      "dual carriageway ends",
      "end of dual carriageway",
      "lanes merge",
      "road becomes single",
      "two lanes to one"
    ]
  },
  {
    "id": "level-crossing-with-barrier-or-gate-ahead",
    "caption": "Level crossing with barrier or gate ahead",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black gate symbol",
    "asset": "UK_traffic_sign_770.svg",
    "diagram": "770",
    "explanation": "A railway level crossing with a barrier or gate is ahead; be ready to stop and never cross while lights flash or barriers are down.",
    "mnemonic": "Gate symbol means a gated crossing.",
    "confusedWith": [
      "level-crossing-without-barrier-or-gate-ahead",
      "trams-crossing-ahead"
    ],
    "searchTerms": [
      "level crossing barrier",
      "railway crossing gate",
      "train crossing ahead",
      "gated level crossing",
      "rail barrier ahead"
    ]
  },
  {
    "id": "level-crossing-without-barrier-or-gate-ahead",
    "caption": "Level crossing without barrier or gate ahead",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black steam-locomotive symbol",
    "asset": "UK_traffic_sign_771.svg",
    "diagram": "771",
    "explanation": "A railway level crossing with no barrier or gate is ahead; slow down, look and listen for trains and obey any signals before crossing.",
    "mnemonic": "Just the train, no gate.",
    "confusedWith": [
      "level-crossing-with-barrier-or-gate-ahead",
      "trams-crossing-ahead"
    ],
    "searchTerms": [
      "level crossing no barrier",
      "open level crossing",
      "railway no gate",
      "train symbol triangle",
      "unguarded crossing"
    ]
  },
  {
    "id": "other-danger",
    "caption": "Other danger",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black exclamation mark on white",
    "asset": "UK_traffic_sign_562.svg",
    "diagram": "562",
    "explanation": "There is a hazard ahead not covered by other signs, usually explained on a plate beneath; slow down and read the plate.",
    "mnemonic": "Exclamation mark = something unexpected.",
    "confusedWith": [],
    "searchTerms": [
      "other danger",
      "exclamation mark sign",
      "hazard ahead",
      "warning triangle",
      "danger sign"
    ]
  },
  {
    "id": "pedestrians-in-road-ahead",
    "caption": "Pedestrians in road ahead",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black symbol of a single person walking",
    "asset": "UK_traffic_sign_544.1.svg",
    "diagram": "544.1",
    "explanation": "Pedestrians may be walking in the road ahead, often where there is no footway; slow down and give them plenty of room.",
    "mnemonic": "One walker = people in the road.",
    "confusedWith": [
      "children",
      "school-crossing-patrol-ahead",
      "frail-or-disabled-pedestrians",
      "zebra-crossing-ahead"
    ],
    "searchTerms": [
      "pedestrians in road",
      "person walking sign",
      "no footpath",
      "people walking",
      "pedestrian warning"
    ]
  },
  {
    "id": "road-narrows-on-both-sides",
    "caption": "Road narrows on both sides",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black lines narrowing inward both sides",
    "asset": "UK_traffic_sign_516.svg",
    "diagram": "516",
    "explanation": "The road narrows from both sides ahead; slow down and be ready to give way or merge as the carriageway gets tighter.",
    "mnemonic": "Both edges squeeze in.",
    "confusedWith": [
      "road-narrows-on-the-right",
      "road-narrows-on-the-left"
    ],
    "searchTerms": [
      "road narrows",
      "narrows both sides",
      "narrow road ahead",
      "carriageway narrows",
      "pinch point"
    ]
  },
  {
    "id": "roundabout",
    "caption": "Roundabout",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, three black curved arrows",
    "asset": "UK_traffic_sign_510.svg",
    "diagram": "510",
    "explanation": "A roundabout is ahead; slow down, get in the correct lane and give way to traffic already on the roundabout (from the right).",
    "mnemonic": "Three arrows chasing in a ring.",
    "confusedWith": [
      "mini-roundabout"
    ],
    "searchTerms": [
      "roundabout ahead",
      "circle junction",
      "give way roundabout",
      "traffic circle",
      "three arrows triangle"
    ]
  },
  {
    "id": "slippery-road",
    "caption": "Slippery road",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black skidding-car symbol on white",
    "asset": "UK_traffic_sign_557.svg",
    "diagram": "557",
    "explanation": "The road ahead may be slippery; ease off the throttle, avoid harsh braking or steering, and keep the bike upright.",
    "mnemonic": "Skid marks = slippery.",
    "confusedWith": [
      "risk-of-ice"
    ],
    "searchTerms": [
      "slippery road",
      "skid",
      "slippery surface",
      "car skidding sign",
      "wet road warning"
    ]
  },
  {
    "id": "steep-hill-downwards",
    "caption": "Steep hill downwards",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black downhill gradient symbol with percentage",
    "asset": "UK_traffic_sign_523.1.svg",
    "diagram": "523.1",
    "explanation": "A steep descent is ahead; select a low gear in good time and use engine braking so you are not relying only on the brakes.",
    "mnemonic": "Arrow points down = going down.",
    "confusedWith": [
      "steep-hill-upwards"
    ],
    "searchTerms": [
      "steep hill down",
      "steep descent",
      "downhill sign",
      "hill with percentage",
      "10% gradient"
    ]
  },
  {
    "id": "t-junction",
    "caption": "T-junction",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black T symbol",
    "asset": "UK_traffic_sign_505.1.svg",
    "diagram": "505.1",
    "explanation": "The road ahead ends at a T-junction; slow down and prepare to give way before turning left or right.",
    "mnemonic": "The road literally hits a 'T'.",
    "confusedWith": [
      "crossroads",
      "staggered-junction",
      "junction-priority-over-minor-road"
    ],
    "searchTerms": [
      "t junction",
      "road ends ahead",
      "give way at top",
      "dead end turn",
      "junction t shape"
    ]
  },
  {
    "id": "traffic-signals-ahead",
    "caption": "Traffic signals ahead",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black traffic-light symbol with red/amber/green",
    "asset": "UK_traffic_sign_543.svg",
    "diagram": "543",
    "explanation": "Traffic lights are ahead, sometimes where you would not expect them; slow down and be ready to stop if they change.",
    "mnemonic": "Mini traffic light in a triangle.",
    "confusedWith": [],
    "searchTerms": [
      "traffic signals ahead",
      "traffic lights ahead",
      "lights ahead warning",
      "signals warning",
      "stoplight ahead"
    ]
  },
  {
    "id": "two-way-traffic",
    "caption": "Two-way traffic",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, two black vertical arrows (one up, one down)",
    "asset": "UK_traffic_sign_521.svg",
    "diagram": "521",
    "explanation": "Traffic ahead flows in both directions, often after a one-way section; keep left and do not overtake unless it is clear.",
    "mnemonic": "Two arrows, two directions.",
    "confusedWith": [
      "one-way-traffic",
      "two-way-traffic-crosses-a-one-way-road"
    ],
    "searchTerms": [
      "two way traffic",
      "traffic both directions",
      "oncoming traffic",
      "two arrows up down",
      "end of one way"
    ]
  },
  {
    "id": "zebra-crossing-ahead",
    "caption": "Zebra crossing ahead",
    "category": "warning",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black symbol of two people on a crossing",
    "asset": "UK_traffic_sign_544.svg",
    "diagram": "544",
    "explanation": "A pedestrian (zebra) crossing is ahead; slow down and be ready to stop for anyone waiting to cross.",
    "mnemonic": "Two figures on stripes = crossing ahead.",
    "confusedWith": [
      "children",
      "school-crossing-patrol-ahead",
      "pedestrians-in-road-ahead",
      "frail-or-disabled-pedestrians"
    ],
    "searchTerms": [
      "zebra crossing",
      "pedestrian crossing ahead",
      "crossing sign",
      "two people crossing",
      "stripes crossing"
    ]
  },
  {
    "id": "accompanied-horses-or-ponies",
    "caption": "Accompanied horses or ponies",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black ridden-horse symbol on white",
    "asset": "UK_traffic_sign_550.1.svg",
    "diagram": "550.1",
    "explanation": "Ridden or led horses may be in or crossing the road ahead; slow right down and pass wide and slow to avoid startling them.",
    "mnemonic": "Horse and rider = pass wide and slow.",
    "confusedWith": [
      "cattle",
      "wild-animals"
    ],
    "searchTerms": [
      "horses ahead",
      "ridden horses",
      "ponies crossing",
      "horse rider sign",
      "accompanied horses"
    ]
  },
  {
    "id": "cattle",
    "caption": "Cattle",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black cow symbol on white",
    "asset": "UK_traffic_sign_548.svg",
    "diagram": "548",
    "explanation": "Cattle may be in or crossing the road ahead; slow down, be ready to stop, and pass any animals slowly and quietly.",
    "mnemonic": "Cow sign = cattle crossing.",
    "confusedWith": [
      "wild-animals",
      "accompanied-horses-or-ponies"
    ],
    "searchTerms": [
      "cattle",
      "cow sign",
      "cows crossing",
      "farm animals",
      "livestock"
    ]
  },
  {
    "id": "distance-to-give-way-line-ahead",
    "caption": "Distance to give way line ahead",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle with inverted-triangle symbol, 'Give Way' plate",
    "asset": "UK_traffic_sign_503.svg",
    "diagram": "503",
    "explanation": "A give way line is the stated distance ahead; start slowing now so you can give way to traffic on the major road.",
    "mnemonic": "Triangle plus a count-down distance.",
    "confusedWith": [
      "distance-to-stop-line-ahead"
    ],
    "searchTerms": [
      "give way ahead",
      "give way 50 yards",
      "yield distance",
      "give way line ahead",
      "slow give way"
    ]
  },
  {
    "id": "distance-to-stop-line-ahead",
    "caption": "Distance to stop line ahead",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle with 'STOP' plate showing distance",
    "asset": "UK_traffic_sign_502.svg",
    "diagram": "502",
    "explanation": "A compulsory STOP line is the stated distance ahead; slow down ready to stop completely at the line.",
    "mnemonic": "Count down, then full stop.",
    "confusedWith": [
      "distance-to-give-way-line-ahead"
    ],
    "searchTerms": [
      "stop ahead",
      "stop in 100 yards",
      "stop line distance",
      "stop sign ahead",
      "approaching stop"
    ]
  },
  {
    "id": "frail-or-disabled-pedestrians",
    "caption": "Frail or disabled pedestrians likely to cross",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black symbol of elderly people with a walking stick",
    "asset": "UK_traffic_sign_544.2.svg",
    "diagram": "544.2",
    "explanation": "Frail or disabled people may be crossing slowly ahead; approach gently and give them extra time to cross.",
    "mnemonic": "Walking stick = slower walkers.",
    "confusedWith": [
      "children",
      "school-crossing-patrol-ahead",
      "pedestrians-in-road-ahead",
      "zebra-crossing-ahead"
    ],
    "searchTerms": [
      "frail pedestrians",
      "elderly crossing",
      "disabled people crossing",
      "old people sign",
      "walking stick crossing"
    ]
  },
  {
    "id": "hump-bridge",
    "caption": "Hump bridge",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black humped-bridge profile symbol on white",
    "asset": "UK_traffic_sign_528.svg",
    "diagram": "528",
    "explanation": "A steep humpback bridge is ahead; slow down so you keep control and do not lose grip or visibility over the crest.",
    "mnemonic": "Bump shape = hump bridge.",
    "confusedWith": [
      "tunnel-ahead",
      "opening-or-swing-bridge-ahead"
    ],
    "searchTerms": [
      "hump bridge",
      "humpback bridge",
      "bumpy bridge",
      "bridge hump",
      "bridge ahead"
    ]
  },
  {
    "id": "junction-priority-over-minor-road",
    "caption": "Junction with priority over minor road",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black T with thinner side road",
    "asset": "UK_traffic_sign_506.1.svg",
    "diagram": "506.1",
    "explanation": "A minor side road joins your road ahead and you have priority; stay alert in case a vehicle pulls out without giving way.",
    "mnemonic": "Thick road is yours, thin road yields.",
    "confusedWith": [
      "crossroads",
      "t-junction",
      "staggered-junction"
    ],
    "searchTerms": [
      "side road ahead",
      "minor road joins",
      "you have priority",
      "side turning right",
      "junction priority"
    ]
  },
  {
    "id": "risk-of-ice",
    "caption": "Risk of ice",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black ice-crystal/snowflake symbol on white",
    "asset": "UK_traffic_sign_554.2.svg",
    "diagram": "554.2",
    "explanation": "The road ahead may be icy or have packed snow; slow down, keep smooth, and allow much greater stopping distance.",
    "mnemonic": "Snowflake = slippery ice.",
    "confusedWith": [
      "slippery-road"
    ],
    "searchTerms": [
      "risk of ice",
      "ice warning",
      "icy road",
      "snowflake sign",
      "black ice"
    ]
  },
  {
    "id": "road-humps-ahead",
    "caption": "Road humps ahead",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black road-hump (bump) symbol",
    "asset": "UK_traffic_sign_557.1.svg",
    "diagram": "557.1",
    "explanation": "Speed-reducing road humps are ahead; slow right down to cross them comfortably and safely.",
    "mnemonic": "Little bump in the triangle.",
    "confusedWith": [],
    "searchTerms": [
      "road humps",
      "speed bumps ahead",
      "humps in road",
      "traffic calming",
      "bumps ahead"
    ]
  },
  {
    "id": "road-narrows-on-the-left",
    "caption": "Road narrows on the left",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black line narrowing in from the left",
    "asset": "UK_traffic_sign_517_(left).svg",
    "diagram": "517",
    "explanation": "The road narrows on the left-hand side ahead; slow down and watch for merging traffic from that side.",
    "mnemonic": "Left edge bends in.",
    "confusedWith": [
      "road-narrows-on-both-sides",
      "road-narrows-on-the-right"
    ],
    "searchTerms": [
      "road narrows left",
      "narrows on left",
      "left side narrows",
      "lane drops left",
      "narrow ahead left"
    ]
  },
  {
    "id": "road-narrows-on-the-right",
    "caption": "Road narrows on the right",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black line narrowing in from the right",
    "asset": "UK_traffic_sign_517_(right).svg",
    "diagram": "517",
    "explanation": "The road narrows on the right-hand side ahead; slow down and watch for merging traffic from that side.",
    "mnemonic": "Right edge bends in.",
    "confusedWith": [
      "road-narrows-on-both-sides",
      "road-narrows-on-the-left"
    ],
    "searchTerms": [
      "road narrows right",
      "narrows on right",
      "right side narrows",
      "lane drops right",
      "narrow ahead right"
    ]
  },
  {
    "id": "school-crossing-patrol-ahead",
    "caption": "School crossing patrol ahead",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black symbol of patrol with STOP-children lollipop",
    "asset": "UK_traffic_sign_547.1.svg",
    "diagram": "547.1",
    "explanation": "A school crossing patrol (lollipop person) may be ahead; be ready to stop when they step into the road with their sign.",
    "mnemonic": "Lollipop ahead = ready to stop.",
    "confusedWith": [
      "children",
      "pedestrians-in-road-ahead",
      "frail-or-disabled-pedestrians",
      "zebra-crossing-ahead"
    ],
    "searchTerms": [
      "school crossing patrol",
      "lollipop man",
      "lollipop lady",
      "crossing patrol",
      "stop children"
    ]
  },
  {
    "id": "side-winds",
    "caption": "Side winds",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black windsock symbol on white",
    "asset": "UK_traffic_sign_581.svg",
    "diagram": "581",
    "explanation": "Strong crosswinds are likely ahead; hold the bike firmly, expect to be pushed sideways, and take care when overtaking or passing gaps.",
    "mnemonic": "Windsock = blown sideways.",
    "confusedWith": [],
    "searchTerms": [
      "side winds",
      "crosswind",
      "windsock sign",
      "strong winds",
      "gusty"
    ]
  },
  {
    "id": "staggered-junction",
    "caption": "Staggered junction",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black staggered-junction symbol",
    "asset": "UK_traffic_sign_507.1.svg",
    "diagram": "507.1",
    "explanation": "Side roads join from alternate sides a short distance apart; slow down and watch for traffic emerging from either side.",
    "mnemonic": "Offset roads, offset symbol.",
    "confusedWith": [
      "crossroads",
      "t-junction",
      "junction-priority-over-minor-road"
    ],
    "searchTerms": [
      "staggered junction",
      "offset side roads",
      "two junctions close",
      "side roads ahead",
      "zigzag junction"
    ]
  },
  {
    "id": "steep-hill-upwards",
    "caption": "Steep hill upwards",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black uphill gradient symbol with percentage",
    "asset": "UK_traffic_sign_524.1.svg",
    "diagram": "524.1",
    "explanation": "A steep climb is ahead; change down to a lower gear early to keep power and momentum up the hill.",
    "mnemonic": "Arrow points up = going up.",
    "confusedWith": [
      "steep-hill-downwards"
    ],
    "searchTerms": [
      "steep hill up",
      "steep climb",
      "uphill sign",
      "hill ahead",
      "20% gradient"
    ]
  },
  {
    "id": "traffic-queues-likely-ahead",
    "caption": "Traffic queues likely ahead",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black queue-of-vehicles symbol",
    "asset": "UK_traffic_sign_584.svg",
    "diagram": "584",
    "explanation": "Queuing traffic is likely on the road ahead; ease off early and be ready to stop to avoid running into the back of a queue.",
    "mnemonic": "Stacked cars mean a queue.",
    "confusedWith": [],
    "searchTerms": [
      "traffic queues",
      "queues likely ahead",
      "congestion ahead",
      "slow traffic ahead",
      "queue warning"
    ]
  },
  {
    "id": "two-way-traffic-crosses-a-one-way-road",
    "caption": "Two-way traffic crosses a one-way road",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, one vertical double-arrow crossing a horizontal up-arrow",
    "asset": "UK_traffic_sign_522.svg",
    "diagram": "522",
    "explanation": "Two-way traffic crosses the one-way road you are on ahead; slow down and look both ways before crossing the junction.",
    "mnemonic": "Up-down arrow cuts across a single arrow.",
    "confusedWith": [
      "two-way-traffic",
      "one-way-traffic"
    ],
    "searchTerms": [
      "two way crosses one way",
      "crossing traffic ahead",
      "two way traffic ahead",
      "one way road crossing",
      "traffic crosses"
    ]
  },
  {
    "id": "uneven-road",
    "caption": "Uneven road",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black bumpy/uneven road symbol",
    "asset": "UK_traffic_sign_556.svg",
    "diagram": "556",
    "explanation": "The road surface ahead is uneven or in poor condition; slow down to keep control and protect the bike.",
    "mnemonic": "Wavy ground, rough road.",
    "confusedWith": [],
    "searchTerms": [
      "uneven road",
      "bumpy road",
      "rough surface ahead",
      "poor road surface",
      "uneven surface"
    ]
  },
  {
    "id": "wild-animals",
    "caption": "Wild animals",
    "category": "warning",
    "tier": "standard",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black leaping deer symbol on white",
    "asset": "UK_traffic_sign_551.svg",
    "diagram": "551",
    "explanation": "Wild animals such as deer may run into the road ahead; reduce speed and stay alert, especially at dawn and dusk.",
    "mnemonic": "Leaping deer = wild animals.",
    "confusedWith": [
      "cattle",
      "accompanied-horses-or-ponies"
    ],
    "searchTerms": [
      "wild animals",
      "deer sign",
      "deer crossing",
      "wildlife",
      "animals ahead"
    ]
  },
  {
    "id": "falling-or-fallen-rocks",
    "caption": "Falling or fallen rocks",
    "category": "warning",
    "tier": "edge",
    "enabled": false,
    "shape": "triangle",
    "colour": "red triangle, black rocks falling down a cliff symbol on white",
    "asset": "UK_traffic_sign_559.svg",
    "diagram": "559",
    "explanation": "Rocks may fall onto, or already lie on, the road ahead; stay alert and be ready to slow or steer around debris.",
    "mnemonic": "Rocks tumbling = watch the road surface.",
    "confusedWith": [],
    "searchTerms": [
      "falling rocks",
      "fallen rocks",
      "rockfall",
      "landslide sign",
      "rocks on road"
    ]
  },
  {
    "id": "low-flying-aircraft",
    "caption": "Low-flying aircraft or sudden aircraft noise",
    "category": "warning",
    "tier": "edge",
    "enabled": false,
    "shape": "triangle",
    "colour": "red triangle, black aeroplane symbol on white",
    "asset": "UK_traffic_sign_558.svg",
    "diagram": "558",
    "explanation": "Low-flying aircraft or sudden loud aircraft noise may startle you ahead, often near an airfield; stay relaxed on the controls and do not be distracted.",
    "mnemonic": "Plane symbol = sudden noise overhead.",
    "confusedWith": [],
    "searchTerms": [
      "low flying aircraft",
      "aircraft noise",
      "aeroplane sign",
      "airfield",
      "planes overhead"
    ]
  },
  {
    "id": "opening-or-swing-bridge-ahead",
    "caption": "Opening or swing bridge ahead",
    "category": "warning",
    "tier": "edge",
    "enabled": false,
    "shape": "triangle",
    "colour": "red triangle, black opening-bridge symbol on white",
    "asset": "UK_traffic_sign_529.svg",
    "diagram": "529",
    "explanation": "An opening or swing bridge is ahead that may be raised or turned for boats; be ready to stop and wait if it is open.",
    "mnemonic": "Bridge lifting = may have to wait.",
    "confusedWith": [
      "tunnel-ahead",
      "hump-bridge"
    ],
    "searchTerms": [
      "opening bridge",
      "swing bridge",
      "lifting bridge",
      "bridge ahead",
      "movable bridge"
    ]
  },
  {
    "id": "overhead-electric-cable",
    "caption": "Overhead electric cable",
    "category": "warning",
    "tier": "edge",
    "enabled": false,
    "shape": "triangle",
    "colour": "red triangle, black overhead-cable symbol with height figure on white",
    "asset": "UK_traffic_sign_779.svg",
    "diagram": "779",
    "explanation": "The road passes under an electrified overhead cable ahead; note the maximum safe height shown and do not exceed it.",
    "mnemonic": "Cable with a height = mind the wire.",
    "confusedWith": [],
    "searchTerms": [
      "overhead cable",
      "electric cable",
      "overhead power line",
      "electrified cable",
      "max height cable"
    ]
  },
  {
    "id": "quayside-or-river-bank",
    "caption": "Quayside or river bank",
    "category": "warning",
    "tier": "edge",
    "enabled": false,
    "shape": "triangle",
    "colour": "red triangle, black car going into water off a quay symbol on white",
    "asset": "UK_traffic_sign_555.svg",
    "diagram": "555",
    "explanation": "There is an unfenced quayside or river bank ahead with a risk of riding into the water; slow down and keep well back from the edge.",
    "mnemonic": "Car off the edge = water ahead.",
    "confusedWith": [],
    "searchTerms": [
      "quayside",
      "river bank",
      "edge of water",
      "dock edge",
      "car into water"
    ]
  },
  {
    "id": "trams-crossing-ahead",
    "caption": "Trams crossing ahead",
    "category": "warning",
    "tier": "edge",
    "enabled": false,
    "shape": "triangle",
    "colour": "red triangle, black tram symbol",
    "asset": "UK_traffic_sign_772.svg",
    "diagram": "772",
    "explanation": "Trams cross or run along the road ahead; slow down, give way to trams and watch for tram rails when turning.",
    "mnemonic": "Tram picture, tram tracks ahead.",
    "confusedWith": [
      "level-crossing-with-barrier-or-gate-ahead",
      "level-crossing-without-barrier-or-gate-ahead"
    ],
    "searchTerms": [
      "trams crossing",
      "tram ahead",
      "tramway warning",
      "tramcar crossing",
      "tram lines ahead"
    ]
  },
  {
    "id": "tunnel-ahead",
    "caption": "Tunnel ahead",
    "category": "warning",
    "tier": "edge",
    "enabled": false,
    "shape": "triangle",
    "colour": "red triangle, black tunnel-mouth symbol on white",
    "asset": "UK_traffic_sign_529.1.svg",
    "diagram": "529.1",
    "explanation": "A tunnel is ahead where light levels change suddenly; remove sunglasses, switch on dipped headlights, and watch for the change in light.",
    "mnemonic": "Black arch = tunnel mouth.",
    "confusedWith": [
      "opening-or-swing-bridge-ahead",
      "hump-bridge"
    ],
    "searchTerms": [
      "tunnel ahead",
      "tunnel sign",
      "road tunnel",
      "tunnel entrance",
      "tunnel warning"
    ]
  },
  {
    "id": "no-through-road",
    "caption": "No through road",
    "category": "information",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "blue square, red and white T symbol",
    "asset": "UK_traffic_sign_816.svg",
    "diagram": "816",
    "explanation": "The road ahead is a dead end with no exit for vehicles, so do not use it as a through route; turn around or find another way.",
    "mnemonic": "The red bar blocks the top of the T - the road stops there.",
    "confusedWith": [],
    "searchTerms": [
      "dead end sign",
      "no through road",
      "cul de sac sign",
      "red t on blue",
      "no exit"
    ]
  },
  {
    "id": "parking",
    "caption": "Parking",
    "category": "information",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "blue square, white letter P",
    "asset": "UK_traffic_sign_801.svg",
    "diagram": "801",
    "explanation": "Marks a parking place where you may legally leave your vehicle; check any plate beneath it for who may park, hours and time limits before you stop.",
    "mnemonic": "P for Park.",
    "confusedWith": [
      "parking-solo-motorcycles",
      "parking-restricted-to-permit-holders"
    ],
    "searchTerms": [
      "parking sign",
      "blue p sign",
      "car park sign",
      "where to park",
      "p on blue"
    ]
  },
  {
    "id": "controlled-parking-zone-end",
    "caption": "End of controlled parking zone",
    "category": "information",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "white sign, blue and red symbol, ZONE ENDS text",
    "asset": "UK_traffic_sign_664.svg",
    "diagram": "664",
    "explanation": "You are leaving the controlled parking zone, so the zone-wide waiting restrictions no longer apply, though any signed restrictions on the next road still do.",
    "confusedWith": [],
    "searchTerms": [
      "end of parking zone",
      "zone ends sign",
      "cpz ends",
      "controlled zone end",
      "leaving parking zone"
    ]
  },
  {
    "id": "controlled-parking-zone-entry",
    "caption": "Entrance to a controlled parking zone",
    "category": "information",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "white sign, blue and red symbol, CONTROLLED ZONE text",
    "asset": "UK_traffic_sign_663.svg",
    "diagram": "663",
    "explanation": "You are entering a controlled parking zone where waiting restrictions apply throughout the zone during the hours shown, so only park in marked bays and read the times.",
    "confusedWith": [],
    "searchTerms": [
      "controlled parking zone",
      "cpz sign",
      "zone entry parking",
      "parking zone start",
      "controlled zone"
    ]
  },
  {
    "id": "hospital",
    "caption": "Hospital",
    "category": "information",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "blue rectangle, white H and word Hospital",
    "asset": "UK_traffic_sign_827.1.svg",
    "diagram": "827.1",
    "explanation": "Points the way to a hospital ahead; this blue version has no accident and emergency department, so do not rely on it in an emergency.",
    "mnemonic": "H for Hospital.",
    "confusedWith": [],
    "searchTerms": [
      "hospital sign",
      "blue h sign",
      "hospital ahead",
      "h on blue",
      "way to hospital"
    ]
  },
  {
    "id": "one-way-traffic",
    "caption": "One-way traffic",
    "category": "information",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "blue rectangle, white upward arrow",
    "asset": "UK_traffic_sign_652.svg",
    "diagram": "652",
    "explanation": "Traffic on this road flows one way only, in the direction the arrow points; continue straight ahead and expect no oncoming vehicles.",
    "mnemonic": "Straight arrow, straight ahead - one way.",
    "confusedWith": [
      "two-way-traffic",
      "two-way-traffic-crosses-a-one-way-road"
    ],
    "searchTerms": [
      "one way sign",
      "one way traffic",
      "blue arrow up sign",
      "single direction road",
      "one way ahead"
    ]
  },
  {
    "id": "parking-solo-motorcycles",
    "caption": "Parking for solo motorcycles",
    "category": "information",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "blue plate, white motorcycle symbol",
    "asset": "UK_traffic_sign_804.4.svg",
    "diagram": "804.4",
    "explanation": "The parking place shown is reserved for solo motorcycles only, so use these bays for your bike and do not park here in a car.",
    "confusedWith": [
      "parking",
      "parking-restricted-to-permit-holders"
    ],
    "searchTerms": [
      "motorcycle parking",
      "solo motorcycle bay",
      "bike parking sign",
      "motorbike parking",
      "parking for bikes"
    ]
  },
  {
    "id": "tourist-information-point",
    "caption": "Tourist information point",
    "category": "information",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "brown sign, white lowercase i",
    "asset": "UK_Tourist_Sign_T1_-_Information.svg",
    "explanation": "Directs you to a tourist information point or centre where you can pick up local maps and visitor guidance; no action is required while riding.",
    "mnemonic": "Lowercase i for information.",
    "confusedWith": [],
    "searchTerms": [
      "tourist information",
      "i sign",
      "information point",
      "brown i sign",
      "visitor information"
    ]
  },
  {
    "id": "bus-lane-junction-ahead",
    "caption": "Bus lane on road at junction ahead",
    "category": "information",
    "tier": "edge",
    "enabled": false,
    "shape": "rectangle",
    "colour": "blue rectangle, white BUSES text and road layout diagram",
    "asset": "UK_traffic_sign_962.svg",
    "diagram": "962",
    "explanation": "Warns that the road you are about to join has a bus lane crossing your path, so watch for buses before you pull out at the junction ahead.",
    "confusedWith": [],
    "searchTerms": [
      "bus lane junction",
      "bus lane ahead sign",
      "buses crossing sign",
      "bus lane at junction",
      "with-flow bus lane"
    ]
  },
  {
    "id": "home-zone-entry",
    "caption": "Home zone entry",
    "category": "information",
    "tier": "edge",
    "enabled": false,
    "shape": "rectangle",
    "colour": "white sign, blue border, scene of houses, people and cyclist",
    "asset": "UK_traffic_sign_881A.svg",
    "diagram": "881A",
    "explanation": "You are entering a home zone designed for people as well as traffic, so drive slowly and give way to pedestrians and children who may be using the whole street.",
    "confusedWith": [],
    "searchTerms": [
      "home zone sign",
      "living street sign",
      "home zone entry",
      "20 zone people sign",
      "shared street sign"
    ]
  },
  {
    "id": "non-primary-route-direction-sign",
    "caption": "Non-primary route direction sign",
    "category": "direction",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "White background, black lettering, route numbers and black border",
    "asset": "",
    "composite": true,
    "explanation": "A white direction sign with black text shows the way along a non-primary route (a local road, including some 'A' and 'B' roads); follow it for your destination.",
    "mnemonic": "White and plain = the local, non-primary lane.",
    "confusedWith": [],
    "searchTerms": [
      "white direction sign",
      "non primary route sign",
      "black and white road sign",
      "local road direction sign",
      "b road sign"
    ]
  },
  {
    "id": "primary-route-direction-sign",
    "caption": "Primary route direction sign",
    "category": "direction",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "Green background, white lettering and borders, yellow route numbers",
    "asset": "",
    "composite": true,
    "explanation": "A green direction sign shows the way along a primary route (a major 'A' road of national or regional importance); follow it for the place name or route number you want.",
    "mnemonic": "Green = Go the main way (primary 'A' roads).",
    "confusedWith": [],
    "searchTerms": [
      "green direction sign",
      "primary route sign",
      "a road sign",
      "green road sign with place names",
      "yellow road number sign"
    ]
  },
  {
    "id": "local-direction-sign",
    "caption": "Local direction sign",
    "category": "direction",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "White background, black lettering and border, often small with no route number",
    "asset": "",
    "composite": true,
    "explanation": "A small white-and-black local direction sign points to nearby places, streets or facilities off the main route; follow it to reach a local destination.",
    "mnemonic": "Small and local: nearby names, no big numbers.",
    "confusedWith": [],
    "searchTerms": [
      "local direction sign",
      "small white road sign",
      "local destination sign",
      "street direction sign",
      "village direction sign"
    ]
  },
  {
    "id": "tourist-attraction-sign",
    "caption": "Tourist attraction sign",
    "category": "direction",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "Brown background, white lettering and symbol",
    "asset": "UK_traffic_sign_2202.svg",
    "diagram": "2202",
    "explanation": "A brown sign with white text or symbol points the way to a tourist attraction or facility; follow it only if that is where you are heading.",
    "mnemonic": "Brown for a day out of town.",
    "confusedWith": [],
    "searchTerms": [
      "brown sign",
      "tourist attraction sign",
      "brown road sign",
      "places of interest sign",
      "tourist information direction"
    ]
  },
  {
    "id": "route-confirmation-sign",
    "caption": "Route confirmation sign",
    "category": "direction",
    "tier": "edge",
    "enabled": false,
    "shape": "rectangle",
    "colour": "Green, white or blue background matching the route, with destinations, route numbers and distances",
    "asset": "",
    "composite": true,
    "explanation": "Sited just after a junction, a route confirmation sign lists destinations ahead with their distances in miles to confirm you are on the right road; read it and carry on.",
    "mnemonic": "After the junction it confirms: right road, miles to go.",
    "confusedWith": [],
    "searchTerms": [
      "route confirmation sign",
      "confirmatory sign",
      "sign with miles after junction",
      "destinations and distances sign",
      "road sign listing towns and miles"
    ]
  },
  {
    "id": "end-of-road-works",
    "caption": "End of road works",
    "category": "roadworks",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "white rectangle, black 'End' text",
    "asset": "",
    "composite": true,
    "explanation": "Marks the end of the road works and of any temporary restrictions, including temporary speed limits; you may return to normal driving for the road.",
    "mnemonic": "'End' means restrictions end.",
    "confusedWith": [],
    "searchTerms": [
      "end of roadworks",
      "end of road works",
      "roadworks finished sign",
      "end restrictions",
      "end speed limit roadworks"
    ]
  },
  {
    "id": "loose-chippings",
    "caption": "Loose chippings",
    "category": "roadworks",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, car throwing up stones",
    "asset": "UK_traffic_sign_7009.svg",
    "diagram": "7009",
    "explanation": "Newly laid surface dressing means loose stone chippings on the road; slow right down to avoid skidding and protect your screen and paintwork from flying chips.",
    "mnemonic": "Loose stones, loose grip - ease off.",
    "confusedWith": [],
    "searchTerms": [
      "loose chippings",
      "loose stones road",
      "loose gravel sign",
      "new surface stones",
      "chippings warning"
    ]
  },
  {
    "id": "road-works",
    "caption": "Road works",
    "category": "roadworks",
    "tier": "core",
    "enabled": true,
    "shape": "triangle",
    "colour": "red triangle, black worker digging symbol",
    "asset": "UK_traffic_sign_7001.svg",
    "diagram": "7001",
    "explanation": "Warns that road works or a temporary obstruction lie ahead; slow down, watch for workers and changed road layout, and be ready to stop.",
    "mnemonic": "Man with a shovel means slow down.",
    "confusedWith": [],
    "searchTerms": [
      "roadworks ahead",
      "men at work sign",
      "construction ahead",
      "worker digging sign",
      "road works triangle"
    ]
  },
  {
    "id": "lane-closed-ahead",
    "caption": "Lane closed ahead",
    "category": "roadworks",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "lane diagram, red bar over closed lane",
    "asset": "",
    "composite": true,
    "explanation": "Shows which traffic lane is closed ahead, marked by a red bar; merge in good time into a lane that stays open and do not change lane at the last moment.",
    "mnemonic": "Red bar = that lane's barred.",
    "confusedWith": [],
    "searchTerms": [
      "lane closed ahead",
      "lane closure sign",
      "merge lane roadworks",
      "red bar lane sign",
      "lane shut motorway"
    ]
  },
  {
    "id": "stop-go-board",
    "caption": "Stop/Go board",
    "category": "roadworks",
    "tier": "standard",
    "enabled": true,
    "shape": "octagon",
    "colour": "red octagon 'STOP' (green 'GO' on reverse)",
    "asset": "UK_traffic_sign_7023.svg",
    "diagram": "7023",
    "explanation": "A manually operated board controlling single-line traffic at road works; obey it exactly - wait at the STOP face and only move on when it is turned to GO.",
    "mnemonic": "Operator's board: STOP means stop, full stop.",
    "confusedWith": [],
    "searchTerms": [
      "stop go board",
      "manual traffic control roadworks",
      "stop sign roadworks",
      "lollipop stop go",
      "traffic controller sign"
    ]
  },
  {
    "id": "temporary-maximum-speed-ahead",
    "caption": "Temporary maximum speed ahead",
    "category": "roadworks",
    "tier": "standard",
    "enabled": true,
    "shape": "circle",
    "colour": "white circle, red ring, black number",
    "asset": "",
    "composite": true,
    "explanation": "Advises the maximum speed in mph that applies through the road works ahead; reduce speed now so you are within the limit before you reach the works.",
    "mnemonic": "Slow before the cones, not at them.",
    "confusedWith": [],
    "searchTerms": [
      "temporary speed limit roadworks",
      "max speed ahead roadworks",
      "roadworks speed limit",
      "50 mph roadworks sign",
      "reduce speed works"
    ]
  },
  {
    "id": "diversion-route",
    "caption": "Diversion route",
    "category": "roadworks",
    "tier": "edge",
    "enabled": false,
    "shape": "rectangle",
    "colour": "yellow rectangle, black 'Diversion' and arrow",
    "asset": "UK_traffic_sign_2702.svg",
    "diagram": "2702",
    "explanation": "Marks a temporary diversion route around a closure or road works; follow the arrow and stay with the diversion symbol at each junction until it ends.",
    "mnemonic": "Follow the symbol all the way round.",
    "confusedWith": [],
    "searchTerms": [
      "diversion sign",
      "diversion route",
      "follow diversion",
      "road closed diversion arrow",
      "detour sign uk"
    ]
  },
  {
    "id": "slow-moving-works-traffic-crossing",
    "caption": "Slow-moving works traffic crossing",
    "category": "roadworks",
    "tier": "edge",
    "enabled": false,
    "shape": "rectangle",
    "colour": "red and white panel, works vehicle symbol",
    "asset": "UK_traffic_sign_7404.svg",
    "diagram": "7404",
    "explanation": "Warns of a slow-moving or stationary works vehicle operating on the carriageway ahead; be ready for it to cross or block a lane and pass only when safe in the direction shown.",
    "mnemonic": "Works vehicle = expect it to crawl.",
    "confusedWith": [],
    "searchTerms": [
      "works vehicle crossing",
      "slow moving works traffic",
      "works lorry on road",
      "highway maintenance vehicle sign",
      "mobile roadworks sign"
    ]
  },
  {
    "id": "double-white-lines-solid-your-side",
    "caption": "Double white lines, solid on your side",
    "category": "marking",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "two white lines along the road centre, the line nearer you solid, the other broken",
    "asset": "",
    "composite": true,
    "explanation": "When the white line nearest you is solid (unbroken) you must not cross or straddle it to overtake; you may only cross to pass a stationary obstruction, turn into a side road or premises, or if directed by police.",
    "mnemonic": "Solid on your side: stay on your side.",
    "confusedWith": [],
    "searchTerms": [
      "double white lines",
      "solid white line in middle",
      "no overtaking line",
      "centre line markings",
      "cannot cross white line"
    ]
  },
  {
    "id": "give-way-markings-at-junction",
    "caption": "Give way markings at a junction",
    "category": "marking",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "a double broken white line across your lane, often with a 'Give Way' triangle painted on the road",
    "asset": "",
    "composite": true,
    "explanation": "Double broken white lines across your half of the road mean give way to traffic on the major road ahead; slow down, be ready to stop, and only go when it is safe.",
    "mnemonic": "Two dashed lines: yield, don't stop sign.",
    "confusedWith": [],
    "searchTerms": [
      "give way road markings",
      "double dashed white line junction",
      "give way triangle on road",
      "broken lines across road",
      "yield markings"
    ]
  },
  {
    "id": "hazard-warning-line",
    "caption": "Hazard warning line",
    "category": "marking",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "a long white centre line with short gaps (dashes longer than the gaps)",
    "asset": "",
    "composite": true,
    "explanation": "A centre line with longer dashes and shorter gaps warns of a hazard ahead, such as a bend or junction; do not cross it unless you can see the road is clear and it is safe.",
    "mnemonic": "Long lines, short gaps: hazard perhaps.",
    "confusedWith": [],
    "searchTerms": [
      "hazard warning line",
      "long white dashes road",
      "centre line longer dashes",
      "warning line ahead",
      "white line bend junction"
    ]
  },
  {
    "id": "yellow-box-junction",
    "caption": "Yellow box junction",
    "category": "marking",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "criss-cross yellow lines painted in a box across the junction",
    "asset": "",
    "composite": true,
    "explanation": "Yellow criss-cross lines mark a box junction you must not enter until your exit is clear, so you do not block the junction; you may wait in the box only when turning right and held up solely by oncoming traffic.",
    "mnemonic": "Keep the box clear: don't enter 'til you can leave.",
    "confusedWith": [],
    "searchTerms": [
      "yellow box junction",
      "criss cross yellow lines",
      "yellow grid on road",
      "box junction markings",
      "do not block junction"
    ]
  },
  {
    "id": "zig-zag-lines-pedestrian-crossing",
    "caption": "Zig-zag lines at a pedestrian crossing",
    "category": "marking",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "white zig-zag lines along both kerbs on the approach to and beyond a crossing",
    "asset": "",
    "composite": true,
    "explanation": "White zig-zag lines mark the controlled area at a pedestrian crossing where you must not park, overtake the lead vehicle, or wait; keep moving and give way to anyone on the crossing.",
    "mnemonic": "Zig-zags: no parking, no overtaking.",
    "confusedWith": [],
    "searchTerms": [
      "zig zag lines crossing",
      "white zigzag road markings",
      "no parking near crossing",
      "zebra crossing lines",
      "pedestrian crossing markings"
    ]
  },
  {
    "id": "flashing-red-stop-lights",
    "caption": "Flashing red stop lights",
    "category": "signal",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "two red lamps side by side flashing alternately",
    "asset": "",
    "composite": true,
    "explanation": "Twin flashing red lights mean you must stop, for example at level crossings, lifting bridges, airfields, fire and ambulance stations; do not cross or pass until the lights stop flashing.",
    "mnemonic": "Reds flashing = full stop, wait until they're off.",
    "confusedWith": [],
    "searchTerms": [
      "flashing red lights",
      "level crossing lights",
      "two red lights flashing",
      "stop lights crossing",
      "red flashing signal"
    ]
  },
  {
    "id": "green-filter-arrow",
    "caption": "Green filter arrow",
    "category": "signal",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "black box with a green arrow lamp lit beside the main lights",
    "asset": "",
    "composite": true,
    "explanation": "A green filter arrow lit at traffic lights means you may move only in the direction the arrow points, whatever the other lights show; do not enter that lane unless you intend to go that way.",
    "mnemonic": "Green arrow = go that way only.",
    "confusedWith": [],
    "searchTerms": [
      "green arrow",
      "filter light",
      "green filter",
      "turning arrow at lights",
      "filter arrow traffic light"
    ]
  },
  {
    "id": "traffic-light-sequence",
    "caption": "Traffic light sequence",
    "category": "signal",
    "tier": "core",
    "enabled": true,
    "shape": "rectangle",
    "colour": "black box with red, amber and green lamps stacked vertically",
    "asset": "",
    "composite": true,
    "explanation": "Traffic lights always follow the order red, then red and amber together, then green, then amber, then back to red; red means stop and red and amber means stop (do not go until green shows), while amber means stop unless you are so close that stopping would be unsafe.",
    "mnemonic": "Red-and-amber is still STOP: get ready, but don't go.",
    "confusedWith": [],
    "searchTerms": [
      "traffic lights",
      "stop lights",
      "red amber green",
      "light sequence",
      "traffic signal order",
      "what does amber mean"
    ]
  },
  {
    "id": "lane-control-signal",
    "caption": "Lane control signal",
    "category": "signal",
    "tier": "standard",
    "enabled": true,
    "shape": "rectangle",
    "colour": "overhead gantry sign: green down-arrow for open lane, red X for closed lane",
    "asset": "",
    "composite": true,
    "explanation": "Overhead lane signals control which lanes you may use: a green downward arrow means the lane is open, a red X means the lane is closed and you must move out of it, and a white diagonal arrow tells you to move to the lane it points to.",
    "mnemonic": "Green down = go, red X = get out of that lane.",
    "confusedWith": [],
    "searchTerms": [
      "lane signals",
      "red x over lane",
      "green arrow overhead",
      "motorway lane control",
      "gantry signals",
      "lane closed sign"
    ]
  }
]
